import sys

DYNAMIC_D3_D4 = -99
DEFICIT_ALLOCATION = -1
LINEAR_ALLOCATION = -2
LINEAR_ALLOCATION_WITH_JUMP = -3
AU_COLUMN_LENGTH = 111
AU_COLUMN_LENGTH_CONNECTIONS = 84
B2B_RDB_COUNT = 20
PROFILE_FARES_QUARTILE = 20
PROFILE_FARES_25PERCENT_QUARTILE = 5
GROUP_QUOTATION =  '{ "Q2": "GJ", "Q4": "GI", "Q6": "GH", "Q8": "GG", "Q10": "GF", "Q12": "GE", "Q14": "GD", "Q16": "GC", "Q18": "GB", "Q20": "GA" }'
B2B_DISCOUNT_MAP = '{ "0": "450", "1": "350", "2": "250", "3": "150" }'

MARKET_FARES_THRESHOLD = '[ {"startNdo": 0, "endNdo": 7, "value": 2}, {"startNdo": 8, "endNdo": 14, "value": 8}, {"startNdo": 15, "endNdo": 21, "value": 48}, {"startNdo": 22, "endNdo": 90, "value": 48}, {"startNdo": 91, "endNdo": 365, "value": 48} ]'

TBF_RBD = "TF,TE,TD,TC,TB,TY"

MIN_D3_D4_VALUE = 2
LINEAR_JUMP_VALUE = 5
PLF_CURVE_VALUE = 0.80
B2B_FARE_PRICE_COMPARISON = 0.9
COVERAGE_PARAMETER = 3
OWN_FARE_DELTA_B = 30
OWN_FARE_DELTA_A = 15
END_OF_DAY_LF_FACTOR = 0.95
PROF_OPEN_COUNT = 10
OVERBOOKING_LF = 95
OVERBOOKING_FARE_LF = 98
OVERBOOKING_FARE_PERCENT_VALUE = 1.1
OVERBOOKING_FARE_ABSOLUTE_VALUE = 1000
OVERBOOKING_START_NDO = 0
OVERBOOKING_END_NDO = 1
OVERBOOKING_PROB = 0.75
OVERBOOKING_MANUAL_LF = 100


S_CLASS_PLF_THRESHOLD = 75
LAST_SOLD_FARE_THRESHOLD = 72
LAST_N_AVG_FARE = 7

MIN_D3_D4_VALUE_KEY = 'MIN_D3_D4_VALUE'
LINEAR_JUMP_VALUE_KEY = 'LINEAR_JUMP_VALUE'
PLF_CURVE_VALUE_KEY = 'PLF_CURVE_VALUE'
B2B_FARE_PRICE_COMPARISON_KEY = 'B2B_FARE_PRICE_COMPARISON'
COVERAGE_PARAMETER_KEY = 'COVERAGE_PARAMETER'
AU_COLUMN_LENGTH_KEY = 'AU_COLUMN_LENGTH'
B2B_RDB_COUNT_KEY = 'B2B_RDB_COUNT'
LOWEST_B2B_RBD_VALUE_KEY = 'LOWEST_B2B_RBD_VALUE'
LOWEST_B2C_RBD_VALUE_KEY = 'LOWEST_B2C_RBD_VALUE'
HIGHEST_B2B_RBD_VALUE_KEY = 'HIGHEST_B2B_RBD_VALUE'
HIGHEST_B2C_RBD_VALUE_KEY = 'HIGHEST_B2C_RBD_VALUE'
OWN_FARE_DELTA_A_KEY = 'OWN_FARE_DELTA_A'
OWN_FARE_DELTA_B_KEY = 'OWN_FARE_DELTA_B'
OVERBOOKING_LF_KEY = 'OVERBOOKING_LF'
END_OF_DAY_LF_FACTOR_KEY = 'END_OF_DAY_LF_FACTOR'
OVERBOOKING_START_NDO_KEY = 'OVERBOOKING_START_NDO'
OVERBOOKING_END_NDO_KEY = 'OVERBOOKING_END_NDO'
OVERBOOKING_PROB_KEY = 'OVERBOOKING_PROB'
S_CLASS_PLF_THRESHOLD_KEY = 'S_CLASS_PLF_THRESHOLD'
AU_COLUMN_LENGTH_CONNECTIONS_KEY='AU_COLUMN_LENGTH_CONNECTIONS'
OVERBOOKING_FARE_PERCENT_VALUE_KEY='OVERBOOKING_FARE_PERCENT_VALUE'
OVERBOOKING_FARE_ABSOLUTE_VALUE_KEY = 'OVERBOOKING_FARE_ABSOLUTE_VALUE'
OVERBOOKING_FARE_LF_KEY = 'OVERBOOKING_FARE_LF'
GROUP_QUOTATION_KEY = 'GROUP_QUOTATION'
TBF_RBD_KEY = 'TBF_RBD'
LAST_SOLD_FARE_THRESHOLD_KEY = 'LAST_SOLD_FARE_THRESHOLD'
LAST_N_AVG_FARE_KEY = 'LAST_N_AVG_FARE'
GROUP_DIFF_FARE_KEY = 'GROUP_DIFF_FARE'
TBF_DIFF_FARE_KEY = 'TBF_DIFF_FARE'
B2B_DISCOUNT_MAP_KEY = 'B2B_DISCOUNT_MAP'
PROF_OPEN_COUNT_KEY = 'PROF_OPEN_COUNT'
MFMIN0_KEY = 'MFMIN0'
MFMIN1_KEY = 'MFMIN1'
CHECK_THRESHOLD_PROCESS_INPUTS_KEY = 'CHECK_THRESHOLD_PROCESS_INPUTS'
OVERBOOKING_MANUAL_LF_KEY = 'OVERBOOKING_MANUAL_LF'

MARKET_FARES_THRESHOLD_KEY = 'MARKET_FARES_THRESHOLD'

LATEST_VERSION = '4.0.0'

TABLE_MARKET_FARES = "market_fares"

WAIT_TIME = 30  # in seconds

AKASA_AIRLINE_CODE = 'QP'

B2C_CHANNEL = "B2C"
B2B_CHANNEL = "B2B"

LOWEST_B2B_RBD_VALUE = 'ZJ'
LOWEST_B2C_RBD_VALUE = 'V9'
HIGHEST_B2B_RBD_VALUE = 'Z0'
HIGHEST_B2C_RBD_VALUE = 'Y'

CONST_ABSOLUTE = 'ABS'
CONST_RELATIVE = 'REL'
CONST_REFERENCE = 'REF'
CONST_NA = 'NA'

DATE_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DATE_TIME_FORMAT2 = '%m/%d/%Y %H:%M'
DATE_FORMAT = "%m/%d/%Y"
DATE_FORMAT_2 = "%Y-%m-%d"
DATE_FORMAT_3 = '%m-%d-%Y'
TIME_FORMAT = '%H:%M'
WEEK_DAY = "%w"
DAY_OF_WEEK = '%A'
MONTH = '%B'
TIME_10_AM = '10:00'
CONST_START_TIME = "00:00"
CONST_END_TIME = "23:59"

TEST_DATA = "TESTDATA"
DB = "DB"
FILE = "FILE"
S3 = "S3"
SKIP = "SKIP"

CONST_API = "api"
CONST_SFTP = "sftp"
CONST_SKIP = "skip"

MIN_FARE_ANCHOR = "MIN"
MAX_FARE_ANCHOR = "MAX"
MINO_FARE_ANCHOR = "MINO"
MAXO_FARE_ANCHOR = "MAXO"
OWNF_FARE_ANCHOR = "OWNF"

YES_FLAG = 'Y'
NO_FLAG = 'N'
FARE_NOT_AVL = -99

CONST_LOGS = "logFiles"
CONST_INPUT_SOURCE = "inputSource"
CONST_OUTPUT = "outputSource"
CONST_CURVES = "Curves"
CONST_MARKET_FARES = "Market_fares"
CONST_MARKET_LIST = "Market_list"
CONST_FARES = "Fares"
CONST_INPUT_STATUS = "inputs_status"
CONST_BOOKLOAD = "bookload"
CONST_OVERBOOKING = "overbooking"
CONST_NDO_BAND = "ndo_bands"
CONST_DPLF_BAND = "dplf_bands"
CONST_DYNAMIC_D1_D2 = "d1_d2_strategies"
CONST_LAST_SELLING_FARE = "lastSellingFare"

CONST_RUN_SUMMARY = "run_summary"
CONST_RUN_AUDIT = "allocation_run_audit"
CONST_SUMMARY_FILE = "Summary"
CONST_AU_GRID = "AUGrid"

CONST_MARKET_LIST_FILE_PATH = f"{sys.path[0]}/params/MarketList.csv"
CONST_MARKET_LIST_CONNECTIONS_FILE_PATH=f"{sys.path[0]}/params/MarketList_Connections.csv"
CONST_AU_GRID_FILE_PATH = f"{sys.path[0]}/output/AUGrid.csv"
CONST_SUMMARY_FILE_PATH = f"{sys.path[0]}/output/summary.csv"
CONST_AU_GRID_CONNECTIONS_FILE_PATH=f"{sys.path[0]}/output/AUGrid_Connections.csv"
CONST_SUMMARY_CONNECTIONS_FILE_PATH = f"{sys.path[0]}/output/summary_Connections.csv"


KEY_B2B_PENDING_COUNT = 'b2b_pending_count_'
KEY_B2C_PENDING_COUNT = 'b2c_pending_count_'
KEY_B2B_READY_COUNT = 'b2b_ready_count_'
KEY_B2C_READY_COUNT = 'b2c_ready_count_'
KEY_B2B_DONE_COUNT = 'b2b_done_count_'
KEY_B2C_DONE_COUNT = 'b2c_done_count_'

TESTING_INPUT = {
    CONST_CURVES: TEST_DATA,
    CONST_MARKET_LIST: TEST_DATA,
    CONST_MARKET_FARES: TEST_DATA,
    CONST_FARES: TEST_DATA,
    CONST_INPUT_STATUS: TEST_DATA,
    CONST_BOOKLOAD: TEST_DATA,
    CONST_NDO_BAND: TEST_DATA,
    CONST_DPLF_BAND: TEST_DATA,
    CONST_DYNAMIC_D1_D2: TEST_DATA,
    CONST_LAST_SELLING_FARE: TEST_DATA,
    CONST_OVERBOOKING: TEST_DATA
}
TESTING_LOGS = {
    CONST_RUN_SUMMARY: SKIP,
    CONST_RUN_AUDIT: SKIP
}
TESTING_OUTPUT = {
    CONST_AU_GRID: FILE,
    CONST_SUMMARY_FILE: FILE
}
SERVER_INPUT = {
    CONST_CURVES: DB,
    CONST_MARKET_LIST: DB,
    CONST_MARKET_FARES: DB,
    CONST_FARES: DB,
    CONST_INPUT_STATUS: DB,
    CONST_BOOKLOAD: DB,
    CONST_NDO_BAND: DB,
    CONST_DPLF_BAND: DB,
    CONST_DYNAMIC_D1_D2: DB,
    CONST_LAST_SELLING_FARE: DB,
    CONST_OVERBOOKING: DB
}
SERVER_LOGS = {
    CONST_RUN_SUMMARY: DB,
    CONST_RUN_AUDIT: DB
}
SERVER_OUTPUT = {
    CONST_AU_GRID: SKIP,
    CONST_SUMMARY_FILE: SKIP
}
LOCAL_INPUT = {
    CONST_CURVES: DB,
    CONST_MARKET_LIST: FILE,
    CONST_MARKET_FARES: DB,
    CONST_FARES: DB,
    CONST_INPUT_STATUS: SKIP,
    CONST_BOOKLOAD: DB,
    CONST_NDO_BAND: DB,
    CONST_DPLF_BAND: DB,
    CONST_DYNAMIC_D1_D2: DB,
    CONST_LAST_SELLING_FARE: DB,
    CONST_OVERBOOKING: DB
}
LOCAL_LOGS = {
    CONST_RUN_SUMMARY: SKIP,
    CONST_RUN_AUDIT: SKIP
}
LOCAL_OUTPUT = {
    CONST_AU_GRID: FILE,
    CONST_SUMMARY_FILE: FILE
}

MFMIN0 = 0
MFMIN1 = 1
CHECK_THRESHOLD_PROCESS_INPUTS = 5
GROUP_DIFF_FARE = 5000
TBF_DIFF_FARE = 2000

HD_NO_REF_CURVE = "No Reference Curve Found"
HD_NO_QP_FARES = "No QP Fares Found"
HD_NO_TBF_FARES = "TBF fares are missing or not found"
HD_NO_REF_CURVE_ID = "unable to get CurevId"
HD_NO_BOOKLOADS = "unable to get Booked loads"
HD_INVALID_CONNECTION = "Connection is invalid"
HD_W0_IS_ONE = "W0 RBD is 1 aborting"


TBF_RBD_QUERY = "'TF','TE','TD','TC','TB','TY'"
TBF_COUNT = 6